// This file is generated by `npm run db:types` using Supabase CLI.
// Placeholder fallback to avoid import errors before generation.
// Replace with your actual Database type after running the command.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, string[]>
    CompositeTypes: Record<string, unknown>
  }
}
